version: '3'

services:
  shopping_cart_app:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
      - CACHE_REDIS_DB=0
      - CACHE_REDIS_URL=redis://redis:6379/0
      - CACHE_REDIS_PASSWORD=redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    hostname: redis-shopping
    restart: on-failure

