apiVersion: v1
kind: Service
metadata:
  name: shopping-cart
spec:
  selector:
    name: shopping-cart
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: shopping-cart
  type: NodePort
