info:
  title: Shopping Cart API
  version: 1.0.0
paths:
  /cart/:
    post:
      summary: Create a shopping cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#./dto/ShoppingCart'
  /cart/detail/{cart_id}:
    get:
      summary: Get details of a specific shopping cart
      parameters:
        - in: path
          name: cart_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShoppingCart'
        '404':
          description: Cart not found
  /cart/list:
    get:
      summary: List all shopping carts
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/ShoppingCart'
  /cart/update/{cart_id}:
    put:
      summary: Update a specific shopping cart
      parameters:
        - in: path
          name: cart_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '204':
          description: Cart updated successfully
        '404':
          description: Cart does not exist
  /cart/{cart_id}:
    delete:
      summary: Delete a specific shopping cart
      parameters:
        - in: path
          name: cart_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cart deleted successfully
        '404':
          description: Cart does not exist
  /cart/{cart_id}/item/add:
    post:
      summary: Add an item to a specific shopping cart
      parameters:
        - in: path
          name: cart_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type
